spring:
  application:
    name: PersonService
  datasource:
    url: jdbc:postgresql://localhost:5438/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: person
server:
  port: 8088
  servlet:
    context-path: /person-service
